server:
  port: 17801

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        namespace: cloudservice
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: cloudservice
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: ${spring.cloud.nacos.config.group}
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/cloudService/user/**