server:
  port: 17802

spring:
  application:
    name: system-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  cloud:
    nacos:
      config:
        namespace: cloudservice
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: cloudservice
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: ${spring.cloud.nacos.config.group}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: io.shadon.cloudservice.system.entity
  configuration:
    map-underscore-to-camel-case: true
